### ISSUE TITLE
Linux build issue

### ISSUE THREAD

**Issue by urijahkeshka** [burhanr13/Tanuki3DS#3]
I have an issue while building in Linux, says:
g++: error: unrecognized command line option ‘-std=gnu++20’; did you mean ‘-std=gnu++2a’?
make: *** [Makefile:63: build/release/pica/hostshaders/hostshaders.o] Error 1
I have all dependencies applied (SDL2, GLEW and Xbyak). and the latest version of g++ (9.4.0-ubuntu20.04.2)
I get these errors after make release command in terminal. What am I doing wrong?

**Comment by burhanr13** [comment]
What is the version of gcc that you have?

**Comment by urijahkeshka** [comment]
gcc version is 9.4.0

**Comment by burhanr13** [comment]
You can either try updating your compiler, or modify the Makefile to use a c++ version supported by your compiler.

**Comment by urijahkeshka** [comment]
Okay I got it built finally. gcc was a pain to upgrade, so I decided to update my linux OS to 22.04. both release file and compilation debugger works!
